import Head from 'next/head'
import Image from 'next/image'
import Collection from './components/collection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Potatoz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=RocknRoll+One&display=block" rel="stylesheet" />
      </Head>


      <div className="bg-dark-900 w-screen h-full text-font-900 pt-24">
        <div className='text-center'>
          <h1 className='text-5xl'>Potatoz</h1>
          <span className='text-xl'>Mint</span>
          <Image src="/assets/potatoz.gif" alt="" className='mx-auto my-4 rounded-lg' width={100} height={100} style={{width: '25vh'}} />
        </div>
        <Collection />
      </div>
    </div>
  )
}
